### PR TITLE
Artboard view onclick

### LINKED ISSUE #30: Create a new page for each finished artboard
When user clicks finish button under artboard, a page with a unique URL is created with:
- the generated Cloudinary image 
- buttons to share on FB, Twitter, Tumblr or download

### LINKED ISSUE #41: URL-encode user-generated text

### PR DESCRIPTION
**Pull request by erasmus**
Fix #30 
Fix #41

### CODE REVIEW

**Comment by erasmus** [comment]
@avorio I tried to take this online. Get 500 Error on the artboard view. 

e.g. https://danandphil-pr-46.herokuapp.com/artboard/v1469544127/mxm3edyfuwednbsmmldx.jpg/?cutout=dp-cutout4.png&text=derp

Could you please have a look?

**Comment by avorio** [comment]
You should turn `Debug = True` to go beyond the Error 500. I'm doing that now.

**Comment by avorio** [comment]
Here's the error:

screen shot 2016-07-26 at 14 26 02

It looks like the database has not been populated. I'm guessing it's because Heroku is not copying the database upon deployment of review branches. I'll investigate now.

**Comment by avorio** [comment]
YES, my assumption was correct. The database for the review branch was empty.

Here's how I solved it (via Heroku CLI):

``` shell
# 'python manage.py migrate' is the Django command to build the database
# Below is how you run that command directly in a Heroku instance
heroku run python manage.py migrate --app danandphil-pr-46
```

Here's the output:

``` shell
Operations to perform:
  Apply all migrations: contenttypes, auth, admin, artboard, sessions
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying artboard.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying sessions.0001_initial... OK
```

Now that URL is generating an error 404, which is expected as the database [structure] has been built but there are no artboards in it. See the troubleshooting image below.

screen shot 2016-07-26 at 14 28 46

**Comment by avorio** [comment]
Yay! Your review branch seems to be working just fine :)

Except for the cutout, which is not the one I chose in the previous screen. See:

screen shot 2016-07-26 at 14 33 47

screen shot 2016-07-26 at 14 33 51

**Comment by avorio** [comment]
I just added the [script to populate the database](https://github.com/degeist/book-cover-generator/pull/46/commits/f1aeb84174473f670a63a99f62a4ebe0ad86640d) to this branch. Let's get this deployed to master eventually so that the next review branches are built properly.

**Comment by erasmus** [comment]
@avorio seems like the migrate script didn't execute?

https://danandphil.herokuapp.com/artboard/v1469557043/l25nhleqyd1lmozcszzn.jpg/?cutout=dp-cutout4.png&text=go%20outside

**Comment by avorio** [comment]
You're right. It didn't. Damn it.

I just executed it manually now and the error 404 is back ON (as it should). All set.

**Comment by erasmus** [comment]
Do I need to run manually after each deploy? Because I get 
screen shot 2016-07-26 at 20 27 38

**Comment by avorio** [comment]
> Do I need to run manually after each deploy?

No, unless you've made changes to the database schema.

But leave that to me anyway, please; I'm the guardian of the models :)

Also, your syntax is incorrect. It's:

```
heroku run [command] --app [name of the app, e.g. 'danandphil']
```

**Comment by erasmus** [comment]
This may be why, the script didn't execute...

screen shot 2016-07-26 at 20 55 18

**Comment by erasmus** [comment]
There was a runaway comma in there...

**Comment by avorio** [comment]
Did you fix it?

**Comment by erasmus** [comment]
Yup

**Comment by avorio** [comment]
Ok, great!

**Pull request merged**
